"""
visualize_graph.py
-------------------
T5.5 — Graph Visualization

Exports the outreach email LangGraph workflow as:
  1. graph_diagram.png   — auto-generated by LangGraph (requires graphviz)
  2. graph_diagram.mmd   — Mermaid source (renders in GitHub, Notion, VS Code)
  3. graph_diagram.md    — Markdown file wrapping the Mermaid block
                           (paste directly into your academic report)

Usage:
    python visualize_graph.py

Requirements:
    pip install -r requirements.txt
    brew install graphviz       # Mac
    sudo apt install graphviz   # Linux
    # Windows: https://graphviz.org/download/

If graphviz is not installed, the PNG export is skipped but the
Mermaid files are always generated.
"""

from __future__ import annotations

from dotenv import load_dotenv
load_dotenv()

from pathlib import Path
from graph import graph

OUTPUT_DIR = Path(__file__).parent / "eval" / "results"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# 1. PNG export via LangGraph (requires graphviz)
# ---------------------------------------------------------------------------

def export_png() -> None:
    try:
        png_bytes = graph.get_graph().draw_mermaid_png()
        path = OUTPUT_DIR / "graph_diagram.png"
        path.write_bytes(png_bytes)
        print(f"PNG exported:      {path}")
    except Exception as exc:
        print(f"PNG export skipped (graphviz may not be installed): {exc}")


# ---------------------------------------------------------------------------
# 2. Mermaid source export via LangGraph
# ---------------------------------------------------------------------------

def export_mermaid() -> None:
    try:
        mermaid_str = graph.get_graph().draw_mermaid()
        path = OUTPUT_DIR / "graph_diagram.mmd"
        path.write_text(mermaid_str, encoding="utf-8")
        print(f"Mermaid exported:  {path}")
        return mermaid_str
    except Exception as exc:
        print(f"Mermaid export failed: {exc}")
        return None


# ---------------------------------------------------------------------------
# 3. Markdown report wrapping the Mermaid block
# ---------------------------------------------------------------------------

_MANUAL_MERMAID = """
flowchart TD
    START([Start]) --> jd_parser
    jd_parser[JD Parser\\nParses raw job description] --> resume_extractor
    resume_extractor[Resume Extractor\\nRanks relevant skills & achievements] --> contact_lookup

    contact_lookup[Contact Lookup\\nApollo.io API search] --> router{Route}

    router -->|Verified email found| email_generator
    router -->|No verified email| linkedin_input

    linkedin_input[LinkedIn Input\\nParses pasted profile context] --> email_generator

    email_generator[Email Generator\\nGenerates email per recipient type] --> subject_generator
    subject_generator[Subject Generator\\nSubject lines + follow-up draft] --> INTERRUPT

    INTERRUPT([INTERRUPT\\nHuman-in-the-loop review]) --> export_node
    export_node[Export Node\\nApplies edits, sets status to drafted] --> END([End])

    style START fill:#E1F5EE,stroke:#0F6E56,color:#085041
    style END fill:#E1F5EE,stroke:#0F6E56,color:#085041
    style INTERRUPT fill:#FAEEDA,stroke:#854F0B,color:#633806
    style router fill:#EEEDFE,stroke:#534AB7,color:#3C3489
    style jd_parser fill:#E6F1FB,stroke:#185FA5,color:#0C447C
    style resume_extractor fill:#E6F1FB,stroke:#185FA5,color:#0C447C
    style contact_lookup fill:#E6F1FB,stroke:#185FA5,color:#0C447C
    style linkedin_input fill:#E6F1FB,stroke:#185FA5,color:#0C447C
    style email_generator fill:#E6F1FB,stroke:#185FA5,color:#0C447C
    style subject_generator fill:#E6F1FB,stroke:#185FA5,color:#0C447C
    style export_node fill:#E6F1FB,stroke:#185FA5,color:#0C447C
""".strip()


def export_markdown(mermaid_str: str | None) -> None:
    diagram = mermaid_str if mermaid_str else _MANUAL_MERMAID

    content = f"""# Outreach Email Feature — LangGraph Workflow

## Graph overview

The workflow is organized into 7 processing nodes plus a human-in-the-loop
interrupt. The conditional router after `contact_lookup` is the key
branching point: if Apollo returns a verified email the graph proceeds
directly to generation; if not, it routes through `linkedin_input` first.

```mermaid
{diagram}
```

## Node responsibilities

| Node | Component | Description |
|---|---|---|
| `jd_parser` | T1.1 | Parses raw JD into structured fields (role, company, skills, responsibilities) |
| `resume_extractor` | T1.2 | Selects top skills and achievements from resume relative to JD |
| `contact_lookup` | T2.1–T2.4 | Queries Apollo.io for verified contact email; triggers fallback on failure |
| `linkedin_input` | T3.1–T3.2 | Parses user-pasted LinkedIn context for personalization signals |
| `email_generator` | T1.3 | Generates personalized email for the target recipient type |
| `subject_generator` | T1.4 | Produces 2–3 subject line options and a follow-up draft |
| `export_node` | T5.4 | Applies user edits from the HITL review and sets outreach status |

## Branching logic

After `contact_lookup`, the conditional router inspects `state["verified_email"]`:

- **Apollo verified email found** → skip `linkedin_input`, go directly to `email_generator`
- **Person found, no verified email** → route through `linkedin_input` for enrichment
- **No person found** → route through `linkedin_input` as LinkedIn message fallback

## Human-in-the-loop (HITL)

The graph uses LangGraph's `interrupt_before` mechanism on `export_node`.
When the graph reaches this point it pauses and returns the generated email
to the caller (UI or Claude Desktop). The user reviews and optionally edits
the email. On the second `graph.invoke()` call with the same `thread_id`,
the graph resumes from the checkpoint and runs `export_node` to finalize.

## State management

All nodes share a single `OutreachState` TypedDict defined in `state.py`.
Nodes return partial state updates — LangGraph merges them automatically.
Two fields (`errors`, `debug_log`) use `operator.add` reducers so each node
can append without overwriting previous entries.
"""

    path = OUTPUT_DIR / "graph_diagram.md"
    path.write_text(content, encoding="utf-8")
    print(f"Markdown exported: {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Exporting LangGraph workflow diagrams...\n")
    export_png()
    mermaid_str = export_mermaid()
    export_markdown(mermaid_str)
    print(f"\nAll outputs written to: {OUTPUT_DIR}")
